FEATURE: Support Flow 7
flownative/flow-token-auth pull request #6
Opened 2021-02-26 15:31 UTC by cvette

2021-03-10 10:53 UTC, bwaidelich commented on Classes/Security/HashToken.php
> +                }
Is that related to Flow 7? Otherwise I'd suggest to extract that to a separate PR so that it can be merged into a lower branch as bugfix

2021-03-10 14:40 UTC, bwaidelich approved these changes

2021-09-03 13:08 UTC, kdambekalns approved these changes

2021-09-03 13:15 UTC, kdambekalns requested changes
Sorry for changing my mind… but even with the adjusted migrations classes, this can work with older versions. Being more strict than the parent is not a problem, see https://3v4l.org/28ije

2021-09-03 13:15 UTC, kdambekalns commented on composer.json
> +        "neos/flow": "^7.0"
```suggestion
        "neos/flow": "^5.0 || ^6.0 || ^7.0"
```

2021-09-03 13:16 UTC, kdambekalns approved these changes

2021-09-03 13:17 UTC, merged